version: '2'
services:
  web:
    image: mulyonoaja/min-jessie
  lb:
    image: dockercloud/haproxy
    links:
     - web
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
